const questionsDB = {

// ═══════════════════════════════════════════════════════════════════════
// DIGITAL ELECTRONICS — 50 questions
// ═══════════════════════════════════════════════════════════════════════
digital: [
  { q:"Decimal equivalent of binary 1101:", options:["11","13","12","14"], answer:1, explanation:"1×2³+1×2²+0×2¹+1×2⁰ = 8+4+0+1 = 13." },
  { q:"AND gate output is 1 only when:", options:["Any input is 1","All inputs are 1","All inputs are 0","Inputs are different"], answer:1, explanation:"AND: output=1 only when ALL inputs=1." },
  { q:"Boolean simplification: A + AB = ?", options:["AB","A+B","A","B"], answer:2, explanation:"A+AB = A(1+B) = A (Absorption law)." },
  { q:"Forbidden state in SR flip-flop:", options:["S=0,R=0","S=1,R=0","S=0,R=1","S=1,R=1"], answer:3, explanation:"S=R=1 → Q=Q'=1, which is contradictory/forbidden." },
  { q:"Flip-flops needed for MOD-6 counter:", options:["2","3","6","4"], answer:1, explanation:"2³=8 ≥ 6, so 3 flip-flops are needed." },
  { q:"XOR output when both inputs are same:", options:["0","1","Undefined","X"], answer:0, explanation:"XOR: same inputs → 0; different inputs → 1." },
  { q:"Decimal 25 in binary:", options:["11001","10011","11010","10101"], answer:0, explanation:"25 = 16+8+1 = 11001₂." },
  { q:"NAND is a universal gate because:", options:["It is cheapest","It has highest speed","Any logic gate can be built using only NAND","It is fastest"], answer:2, explanation:"NAND (and NOR) are universal — any Boolean function can be implemented with only NAND gates." },
  { q:"2's complement of binary 0110:", options:["1001","1010","1110","0110"], answer:1, explanation:"1's complement of 0110 = 1001. Add 1 → 1010." },
  { q:"Gray code of decimal 7:", options:["0111","0100","0101","1000"], answer:1, explanation:"Binary 7=0111. Gray: MSB same, each bit = XOR of adjacent binary bits → 0100." },
  { q:"D flip-flop output Q after clock edge:", options:["Q=D'","Q=Q_prev","Q=D","Q=0"], answer:2, explanation:"D flip-flop: Q = D at every clock edge." },
  { q:"Octal 17 equals decimal:", options:["15","17","8","14"], answer:0, explanation:"1×8¹+7×8⁰ = 8+7 = 15." },
  { q:"Full adder has how many inputs?", options:["1","2","3","4"], answer:2, explanation:"Full adder: A, B, and Carry-in = 3 inputs." },
  { q:"Hexadecimal F equals decimal:", options:["16","14","15","13"], answer:2, explanation:"F is the 16th hex digit = 15 in decimal." },
  { q:"In a synchronous counter:", options:["FFs trigger sequentially","All FFs share a common clock","No clock is used","Only D FFs are used"], answer:1, explanation:"Synchronous: all flip-flops clocked simultaneously." },
  { q:"Which memory is volatile?", options:["ROM","Flash","EEPROM","RAM"], answer:3, explanation:"RAM loses data when power is off — volatile." },
  { q:"Boolean expression for XNOR gate:", options:["A⊕B","A'+B'","(A⊕B)'","A·B"], answer:2, explanation:"XNOR = complement of XOR = (A⊕B)'." },
  { q:"Which logic family has highest noise margin?", options:["TTL","CMOS","ECL","DTL"], answer:1, explanation:"CMOS has highest noise margin (~45% of VDD)." },
  { q:"JK flip-flop when J=1, K=1:", options:["Set","Reset","No change","Toggle"], answer:3, explanation:"J=K=1 causes the flip-flop to toggle its output." },
  { q:"In a 2-variable K-map, number of cells:", options:["2","4","6","8"], answer:1, explanation:"2 variables → 2² = 4 cells." },
  // --- new questions ---
  { q:"De Morgan's theorem: (A·B)' = ?", options:["A'·B'","A'+B'","A·B","A+B"], answer:1, explanation:"(A·B)' = A' + B'. Complement of AND = OR of complements." },
  { q:"Minimum 2-input NAND gates to implement AND:", options:["1","2","3","4"], answer:1, explanation:"AND using NAND: first NAND, then invert output with another NAND (connected as inverter)." },
  { q:"Maximum count of a 4-bit binary counter:", options:["14","15","16","12"], answer:1, explanation:"4-bit: 2⁴ - 1 = 15 (states 0000 to 1111)." },
  { q:"SOP stands for:", options:["Sum of Products","System of Protocols","Series of Products","Set of Parameters"], answer:0, explanation:"SOP = Sum of Products form of Boolean expression." },
  { q:"BCD code for decimal 9:", options:["1001","1010","1100","0111"], answer:0, explanation:"BCD: each decimal digit encoded in 4 bits. 9 = 1001." },
  { q:"Excess-3 code is obtained from BCD by adding:", options:["1","2","3","5"], answer:2, explanation:"Excess-3 = BCD + 0011 (adding decimal 3 to each BCD digit)." },
  { q:"4-to-1 MUX needs ___ select lines:", options:["1","2","3","4"], answer:1, explanation:"2ⁿ ≥ 4 → n = 2 select lines." },
  { q:"Which is NOT a valid BCD combination?", options:["0111","1001","1011","0101"], answer:2, explanation:"BCD uses only 0000–1001 (0–9). 1011 = decimal 11, which is invalid BCD." },
  { q:"JK flip-flop with J=0, K=0:", options:["Resets","Sets","Toggles","No change (hold state)"], answer:3, explanation:"J=K=0: no change. J=1,K=0: Set. J=0,K=1: Reset. J=K=1: Toggle." },
  { q:"Decimal 255 in hexadecimal:", options:["FF","EE","FE","EF"], answer:0, explanation:"255 = 15×16 + 15 = 0xFF." },
  { q:"In a ripple counter, clock is applied to:", options:["All FFs simultaneously","Only the last FF","Only the first FF","External decoder"], answer:2, explanation:"Ripple (asynchronous) counter: clock to first FF; each subsequent FF triggered by previous FF output." },
  { q:"Boolean expression A'B + AB' equals:", options:["A·B","A+B","A⊕B (XOR)","A'B'"], answer:2, explanation:"A'B + AB' is the definition of A XOR B." },
  { q:"1's complement of 1010 is:", options:["0110","0101","1010","1111"], answer:1, explanation:"1's complement: flip every bit. 1010 → 0101." },
  { q:"D flip-flop is used in registers because:", options:["It is cheapest","It directly stores one bit (Q = D)","It toggles on every clock","It has no clock input"], answer:1, explanation:"D flip-flop: Q = D at clock edge, so it stores the bit presented at D." },
  { q:"Fan-out of a gate indicates:", options:["Input capacitance","Number of gates it can reliably drive","Power consumption","Propagation delay"], answer:1, explanation:"Fan-out = number of standard load inputs that can be driven from one output without degradation." },
  { q:"Number of minterms in a 3-variable Boolean function:", options:["3","6","8","16"], answer:2, explanation:"n variables → 2ⁿ minterms. n=3: 2³ = 8 minterms." },
  { q:"Half adder has outputs:", options:["Sum only","Carry only","Sum and Carry","Sum, Carry, and Borrow"], answer:2, explanation:"Half adder: S = A⊕B (XOR), Cout = A·B (AND)." },
  { q:"Which logic family consumes least static power?", options:["TTL","ECL","CMOS","DTL"], answer:2, explanation:"CMOS: no direct path between VDD and GND in steady state → nearly zero static power." },
  { q:"A 3-to-8 decoder: exactly ___ output(s) is HIGH for any input:", options:["3","2","1","All 8"], answer:2, explanation:"Decoder: exactly one of 8 outputs is HIGH corresponding to the 3-bit binary input." },
  { q:"Propagation delay in gates limits the:", options:["DC voltage levels","Maximum operating frequency","Output voltage swing","Fan-in"], answer:1, explanation:"fmax = 1/(sum of propagation delays in critical path)." },
  { q:"Which number system uses base 8?", options:["Binary","Decimal","Octal","Hexadecimal"], answer:2, explanation:"Octal = base-8 system using digits 0–7." },
  { q:"A T flip-flop with T=1 at each clock:", options:["Holds state","Resets","Sets","Toggles on every clock"], answer:3, explanation:"T flip-flop: T=1 → toggle; T=0 → hold. Useful for binary counters." },
  { q:"The output of NOR gate when all inputs are 0:", options:["0","1","Undefined","High-Z"], answer:1, explanation:"NOR = NOT(OR). All inputs 0 → OR = 0 → NOR = 1." },
  { q:"Binary subtraction: use 2's complement of:", options:["Minuend","Subtrahend","Both","Neither"], answer:1, explanation:"Binary subtraction A-B: take 2's complement of B, add to A, discard carry." },
  { q:"Karnaugh map groups must be powers of:", options:["3","10","2","5"], answer:2, explanation:"K-map groups must contain 1, 2, 4, 8... (powers of 2) cells." },
  { q:"POS stands for:", options:["Product of Sums","Power of Sum","Pair of Sequences","Pulse Output Sequence"], answer:0, explanation:"POS = Product of Sums — an alternative canonical form of Boolean expression." },
  { q:"A MOD-10 (decade) counter counts:", options:["0 to 9","0 to 10","1 to 10","0 to 15"], answer:0, explanation:"MOD-10 counter: cycles through 0 to 9 (10 states). Used in BCD counters." },
  { q:"Dual of A·1 = A is:", options:["A+0=A","A·0=0","A+1=1","A·1=A"], answer:2, explanation:"Duality: swap AND↔OR and 0↔1. A·1=A → A+0=A. But dual of A·1=A is A+0=A. Hmm — the dual operation swaps · with + and 1 with 0. A·1=A dual: A+0=A." },
  { q:"In SRAM, data is stored using:", options:["Capacitor charge","Flip-flop (bistable circuit)","Magnetic domain","Optical medium"], answer:1, explanation:"SRAM: data stored in flip-flops (6 transistors per cell). Faster but larger than DRAM." },
  { q:"The advantage of a carry-lookahead adder over ripple-carry:", options:["Uses fewer transistors","All carries computed in parallel — faster","Lower power","No carry generation needed"], answer:1, explanation:"CLA generates all carry signals simultaneously, eliminating sequential carry propagation delay." },
  { q:"Hexadecimal 1A in decimal:", options:["16","26","28","30"], answer:1, explanation:"1A hex = 1×16 + 10 = 26." },
],

// ═══════════════════════════════════════════════════════════════════════
// NETWORK THEORY — 40 questions
// ═══════════════════════════════════════════════════════════════════════
network: [
  { q:"KVL states the algebraic sum of voltages in a closed loop is:", options:["Maximum","Minimum","Zero","Infinity"], answer:2, explanation:"Kirchhoff's Voltage Law: ΣV = 0 around any closed loop." },
  { q:"KCL states the algebraic sum of currents at a node is:", options:["Zero","Maximum power","One","Equal to source voltage"], answer:0, explanation:"Kirchhoff's Current Law: ΣI = 0 at any node (current in = current out)." },
  { q:"Thevenin equivalent consists of:", options:["Current source in parallel with R","Voltage source in series with R","Two resistors","Current source only"], answer:1, explanation:"Thevenin: Vth in series with Rth." },
  { q:"Norton equivalent consists of:", options:["Voltage source in series with R","Current source in parallel with R","Capacitor and R","Inductor only"], answer:1, explanation:"Norton: IN in parallel with RN (= Rth)." },
  { q:"Norton current IN equals:", options:["Vth × Rth","Vth / Rth","Rth / Vth","1/Vth"], answer:1, explanation:"IN = Vth/Rth (short-circuit current at terminals)." },
  { q:"For maximum power transfer, RL =", options:["0","Infinity","Rth","2×Rth"], answer:2, explanation:"Maximum power when RL = Rth." },
  { q:"Time constant of RC circuit:", options:["R/C","RC","1/RC","R+C"], answer:1, explanation:"τ = RC. Defines capacitor charge/discharge rate." },
  { q:"Superposition theorem applies to:", options:["All circuits","Non-linear only","Linear circuits only","Resistors only"], answer:2, explanation:"Superposition applies only to linear circuits." },
  { q:"Power factor of purely inductive circuit:", options:["Unity","Zero leading","Zero lagging","0.5 lagging"], answer:2, explanation:"Pure inductor: current lags voltage 90°, PF = cos 90° = 0 (lagging)." },
  { q:"Series RLC at resonance, impedance is:", options:["Zero","Purely reactive","Purely resistive (R)","Maximum"], answer:2, explanation:"At resonance XL = XC, they cancel. Z = R only." },
  { q:"Quality factor Q of series RLC:", options:["ωL/R","R/ωL","ωC/R","ωLC"], answer:0, explanation:"Q = ωL/R = 1/(ωCR). Higher Q → sharper resonance." },
  { q:"Parallel resonance impedance is:", options:["Zero","Minimum","Maximum","Equal to R"], answer:2, explanation:"Parallel resonance: impedance is maximum (ideally infinite)." },
  { q:"Impedance of inductor in frequency domain:", options:["jωC","1/jωC","jωL","ωL"], answer:2, explanation:"ZL = jωL." },
  { q:"Impedance of capacitor in frequency domain:", options:["jωC","1/jωC","jω/C","ωC"], answer:1, explanation:"ZC = 1/jωC." },
  { q:"Nodal analysis is based on:", options:["KVL","Superposition","KCL","Thevenin theorem"], answer:2, explanation:"Nodal analysis applies KCL at each independent node." },
  { q:"Mesh analysis is based on:", options:["KCL","KVL","Norton theorem","Superposition"], answer:1, explanation:"Mesh analysis applies KVL around each mesh loop." },
  { q:"Maximum power transferred = ?", options:["Vth/4Rth","Vth²/4Rth","2Vth/Rth","Vth²/Rth"], answer:1, explanation:"Pmax = Vth²/(4Rth) when RL = Rth." },
  { q:"Time constant of RL circuit:", options:["RL","L/R","R/L","1/RL"], answer:1, explanation:"τ = L/R for RL circuit." },
  { q:"Resonant frequency of LC circuit:", options:["1/(2π√LC)","2π√LC","1/(2πLC)","2π/√LC"], answer:0, explanation:"f₀ = 1/(2π√LC)." },
  { q:"Reciprocity theorem applies to:", options:["Non-linear circuits","Active circuits","Linear bilateral networks","All circuits"], answer:2, explanation:"Reciprocity: excitation and response can be interchanged in linear bilateral passive networks." },
  // --- new questions ---
  { q:"Two resistors R1 and R2 in series, equivalent resistance:", options:["R1×R2/(R1+R2)","R1+R2","R1−R2","√(R1×R2)"], answer:1, explanation:"Series: Req = R1 + R2." },
  { q:"Two resistors R1 and R2 in parallel, equivalent resistance:", options:["R1+R2","R1R2/(R1+R2)","R1−R2","(R1+R2)/2"], answer:1, explanation:"Parallel: Req = R1R2/(R1+R2)." },
  { q:"If voltage doubles across a resistor, power consumption:", options:["Doubles","Halves","Quadruples","Remains same"], answer:2, explanation:"P = V²/R. V→2V: P = (2V)²/R = 4P. Power quadruples." },
  { q:"Supernode in nodal analysis is formed when:", options:["Current source is between two nodes","Voltage source is between two non-reference nodes","Dependent source is present","Ground is at infinity"], answer:1, explanation:"Supernode: voltage source between two non-reference nodes — combine them as one supernode." },
  { q:"RMS value of sinusoidal voltage V = Vm·sin(ωt):", options:["Vm","Vm/√2","Vm/2","2Vm/π"], answer:1, explanation:"VRMS = Vm/√2 for sinusoidal signals." },
  { q:"Source transformation: current source I parallel with R → equivalent:", options:["Voltage source I/R in series with R","Voltage source IR in series with R","Voltage source IR parallel with R","Remains same"], answer:1, explanation:"V = IR in series with R (source transformation)." },
  { q:"Bandwidth of series RLC circuit:", options:["ω₀/Q","Q/ω₀","ω₀Q","1/ω₀Q"], answer:0, explanation:"BW = ω₀/Q = R/L. Higher Q = narrower bandwidth." },
  { q:"Transient response of RC circuit to step input:", options:["Linear","Quadratic","Exponential","Sinusoidal"], answer:2, explanation:"v(t) = V(1−e^(−t/RC)) — exponential approach to steady state." },
  { q:"Energy stored in a capacitor C charged to voltage V:", options:["CV","½CV²","CV²","C²V"], answer:1, explanation:"E = ½CV²." },
  { q:"Energy stored in an inductor L carrying current I:", options:["LI","½LI²","LI²","L²I"], answer:1, explanation:"E = ½LI²." },
  { q:"Thevenin voltage Vth is the ___ voltage at the terminals:", options:["Short circuit","Open circuit","Maximum power","Average"], answer:1, explanation:"Vth = open-circuit voltage (with load disconnected)." },
  { q:"In a delta-star transformation, each star resistor R_Y = ?", options:["Sum of delta R","Product of adjacent delta R / sum of all three delta R","(Sum of delta R)/3","Delta R/3"], answer:1, explanation:"R_Y = (R_Δ1 × R_Δ2)/(R_Δ1 + R_Δ2 + R_Δ3) for adjacent resistors." },
  { q:"Mutual inductance M between two coils is:", options:["M = k/(L1L2)","M = k√(L1L2)","M = k(L1+L2)","M = kL1L2"], answer:1, explanation:"M = k√(L1L2), where k = coupling coefficient (0 ≤ k ≤ 1)." },
  { q:"Power factor correction for lagging load: add a ___ in parallel:", options:["Inductor","Resistor","Capacitor","Battery"], answer:2, explanation:"Inductive (lagging) loads need a capacitor in parallel to improve (raise) power factor toward unity." },
  { q:"Tellegen's theorem states:", options:["Sum of branch powers = 0","Sum of voltages = 0","Sum of currents = 1","Sum of impedances = constant"], answer:0, explanation:"Tellegen: sum of instantaneous power in all branches = 0 (power conservation)." },
  { q:"In a transformer with turns ratio N1:N2 = 1:5, if V1 = 10 V, V2 = ?", options:["2 V","50 V","10 V","0.5 V"], answer:1, explanation:"V2/V1 = N2/N1 = 5. V2 = 50 V." },
  { q:"A 1 μF capacitor charged to 10 V stores energy:", options:["5 μJ","10 μJ","50 μJ","100 μJ"], answer:2, explanation:"E = ½ × 1×10⁻⁶ × 10² = 50 μJ." },
  { q:"The h-parameter h11 of a two-port network is:", options:["Output impedance","Input impedance with output short-circuited","Current gain","Voltage gain"], answer:1, explanation:"h11 = V1/I1 with V2 = 0 (output shorted) = input impedance." },
  { q:"Impedance Z = R + jX. The reactive component jX is:", options:["Always resistive","Due to inductors and capacitors","Negative always","Due to resistors"], answer:1, explanation:"Reactive component X = XL − XC (inductive and capacitive reactances)." },
  { q:"In AC circuit, average power P = VrmsIrms×:", options:["sin(θ)","tan(θ)","cos(θ) — power factor","1"], answer:2, explanation:"P = Vrms × Irms × cos(θ), where θ is the phase angle between V and I." },
],

// ═══════════════════════════════════════════════════════════════════════
// ANALOG ELECTRONICS — 45 questions
// ═══════════════════════════════════════════════════════════════════════
analog: [
  { q:"Depletion region in PN junction is formed by:", options:["Applied voltage","Diffusion of majority carriers","External current","Doping alone"], answer:1, explanation:"Diffusion of majority carriers across the junction creates the depletion region." },
  { q:"Forward bias voltage for silicon diode:", options:["0.3V","1.0V","0.7V","1.4V"], answer:2, explanation:"Silicon diode: Vf ≈ 0.7 V. Germanium ≈ 0.3 V." },
  { q:"Zener diode operates in:", options:["Forward bias only","Both forward and reverse","Reverse breakdown region","Unbiased condition"], answer:2, explanation:"Zener works in reverse breakdown for voltage regulation." },
  { q:"BJT current gain β = ?", options:["IE/IB","IC/IE","IC/IB","IB/IC"], answer:2, explanation:"β = IC/IB. Typical β: 50–300." },
  { q:"MOSFET is a ___ controlled device:", options:["Current","Voltage","Power","Resistance"], answer:1, explanation:"MOSFET: gate voltage controls drain current." },
  { q:"Phase shift in common emitter amplifier:", options:["0°","90°","180°","270°"], answer:2, explanation:"CE amplifier: output is 180° out of phase with input." },
  { q:"Ripple factor of full-wave rectifier:", options:["1.21","0.482","0.707","2.0"], answer:1, explanation:"Full-wave ripple factor = 0.482 (resistive load)." },
  { q:"PIV of a bridge rectifier:", options:["Vm","2Vm","Vm/2","√2 Vm"], answer:0, explanation:"Bridge rectifier PIV = Vm (lower than centre-tap FWR which is 2Vm)." },
  { q:"Efficiency of full-wave rectifier:", options:["40.6%","81.2%","50%","100%"], answer:1, explanation:"FWR theoretical efficiency = 81.2%." },
  { q:"N-channel enhancement MOSFET conducts when VGS:", options:["Is negative","Exceeds threshold VT","Is zero","Equals VDS"], answer:1, explanation:"Enhancement MOSFET: channel forms only when VGS > VT." },
  { q:"Common collector (emitter follower) configuration:", options:["High voltage gain","180° phase shift","Low input impedance","High Zin, low Zout, gain ≈ 1"], answer:3, explanation:"CC: high Zin, low Zout, Av ≈ 1, no phase inversion." },
  { q:"Barkhausen criterion for sustained oscillations:", options:["|Aβ| > 1","Phase = 90°","|Aβ| = 1, total phase = 0° or 360°","|Aβ| < 1"], answer:2, explanation:"Barkhausen: loop gain |Aβ| = 1, total loop phase = 0° or 360°." },
  { q:"Ideal op-amp input impedance:", options:["Zero","1kΩ","Infinite","100Ω"], answer:2, explanation:"Ideal op-amp: Zin = ∞, Zout = 0, open-loop gain = ∞." },
  { q:"Inverting op-amp amplifier gain:", options:["Rf/Rin","−Rf/Rin","Rin/Rf","1+Rf/Rin"], answer:1, explanation:"Inverting gain = −Rf/Rin (negative sign = 180° phase inversion)." },
  { q:"CMRR of ideal op-amp:", options:["Zero","Unity","Infinite","100 dB"], answer:2, explanation:"Ideal op-amp: CMRR = ∞ (perfectly rejects common-mode signals)." },
  { q:"Class A amplifier maximum efficiency:", options:["25%","50%","78.5%","100%"], answer:1, explanation:"Class A: max η = 25% (resistive load) or 50% (transformer-coupled)." },
  { q:"Class B amplifier maximum efficiency:", options:["25%","50%","78.5%","100%"], answer:2, explanation:"Class B: max η = π/4 ≈ 78.5%." },
  { q:"Pinch-off voltage is associated with:", options:["BJT","Enhancement MOSFET","JFET","Zener diode"], answer:2, explanation:"JFET pinch-off voltage VP: VGS at which channel current cuts off." },
  { q:"Non-inverting op-amp gain:", options:["Rf/Rin","−Rf/Rin","1+Rf/Rin","1−Rf/Rin"], answer:2, explanation:"Non-inverting: Av = 1 + Rf/Rin (always positive, no inversion)." },
  { q:"Hartley oscillator feedback network uses:", options:["Two capacitors + one inductor","Two inductors + one capacitor","RC ladder","Zener diode"], answer:1, explanation:"Hartley: tapped inductor (two L's) + one capacitor. Colpitts uses two C's + one L." },
  // --- new questions ---
  { q:"Intrinsic semiconductor conductivity with increasing temperature:", options:["Decreases","Remains constant","Increases (more e-h pairs)","Becomes zero"], answer:2, explanation:"Higher temperature → more electron-hole pairs generated → higher conductivity." },
  { q:"Reverse saturation current IS of diode with temperature:", options:["Decreases","Remains constant","Approximately doubles every 10°C","Halves every 10°C"], answer:2, explanation:"IS approximately doubles for every 10°C rise in temperature." },
  { q:"Early effect in BJT causes:", options:["Change in VBE","Reduction in base width with increasing VCE","Decrease in collector current","Change in emitter resistance"], answer:1, explanation:"Early effect (base-width modulation): increasing VCE reduces effective base width, increasing IC." },
  { q:"Class AB amplifier transistors conduct for:", options:["Full 360°","Exactly 180°","Slightly more than 180°","90°"], answer:2, explanation:"Class AB: each transistor conducts slightly more than 180° — eliminates crossover distortion." },
  { q:"Gain-bandwidth product (GBW) of op-amp:", options:["Varies with frequency","Is constant","Equals open-loop gain","Equals slew rate"], answer:1, explanation:"GBW = constant. Decreasing closed-loop gain increases bandwidth proportionally." },
  { q:"Slew rate of op-amp is defined as:", options:["Maximum dVout/dt","Input offset voltage","Bandwidth × gain","Output short-circuit current"], answer:0, explanation:"Slew rate = maximum rate of change of output voltage (V/μs)." },
  { q:"In a bridge rectifier, during the positive half cycle:", options:["All 4 diodes conduct","D1 and D3 (one diagonal pair) conduct","D2 and D4 conduct","Only D1 conducts"], answer:1, explanation:"Bridge rectifier: diagonal pairs conduct alternately." },
  { q:"Average output voltage of half-wave rectifier:", options:["Vm","Vm/2","Vm/π","2Vm/π"], answer:2, explanation:"HWR average Vavg = Vm/π ≈ 0.318 Vm." },
  { q:"Average output voltage of full-wave rectifier:", options:["Vm/π","2Vm/π","Vm/2","Vm/√2"], answer:1, explanation:"FWR average Vavg = 2Vm/π ≈ 0.636 Vm." },
  { q:"IC 555 timer in astable (free-running) mode produces:", options:["A single pulse","Continuous square wave","Sawtooth wave","DC level"], answer:1, explanation:"555 astable: free-running oscillator producing continuous rectangular waveform." },
  { q:"Threshold voltage VT of N-channel enhancement MOSFET is:", options:["Negative","Zero","Positive","Equal to VDD"], answer:2, explanation:"N-channel enhancement MOSFET: VT > 0. Channel forms only when VGS > VT." },
  { q:"Current gain α of BJT (common base) = ?", options:["IC/IE","IB/IC","IE/IC","IC/IB"], answer:0, explanation:"α = IC/IE ≈ 0.95–0.999. Related to β: α = β/(β+1)." },
  { q:"Wien bridge oscillator frequency f₀ = ?", options:["1/(2πRC)","1/(πRC)","2πRC","πRC"], answer:0, explanation:"Wien bridge oscillator frequency f₀ = 1/(2πRC)." },
  { q:"Op-amp integrator output is:", options:["Differentiated input","Proportional to input","−(1/RC)∫Vin dt","Rectified input"], answer:2, explanation:"Integrator: Vout = −(1/RC)∫Vin dt." },
  { q:"Transistor in saturation mode:", options:["VCE ≈ 0.7 V","Both E-B and C-B junctions forward biased","Both junctions reverse biased","Used in linear amplifiers"], answer:1, explanation:"Saturation: both E-B and C-B junctions forward biased. VCE(sat) ≈ 0.2 V (BJT in ON state)." },
  { q:"Varactor (varicap) diode is used as:", options:["Voltage regulator","Variable capacitor (reverse-biased)","Constant current source","Oscillator only"], answer:1, explanation:"Varactor: junction capacitance varies with reverse voltage. Used in VCOs and tuners." },
  { q:"Negative feedback in amplifiers:", options:["Reduces distortion and bandwidth","Increases distortion","Reduces gain but increases bandwidth and stability","Increases noise"], answer:2, explanation:"Negative feedback: reduces distortion, stabilises gain, reduces noise, INCREASES bandwidth." },
  { q:"An op-amp Schmitt trigger uses:", options:["Negative feedback only","Positive feedback (hysteresis)","Capacitor in feedback","Integrator configuration"], answer:1, explanation:"Schmitt trigger: positive feedback creates hysteresis — converts noisy signals to clean digital output." },
  { q:"Depletion mode MOSFET conducts at VGS = 0 because:", options:["Gate has positive charge","Channel is implanted during fabrication — exists at VGS=0","Threshold voltage is zero","It requires gate current"], answer:1, explanation:"Depletion MOSFET: physical channel exists due to implantation. Conducts at VGS=0." },
  { q:"The base-emitter voltage VBE of a forward-biased silicon BJT:", options:["0.3 V","0.7 V","1.4 V","5 V"], answer:1, explanation:"Silicon BJT in active region: VBE ≈ 0.7 V." },
  { q:"CMRR of differential amplifier in dB:", options:["20 log(Ad/Ac)","20 log(Ac/Ad)","10 log(Ad/Ac)","log(Ad+Ac)"], answer:0, explanation:"CMRR(dB) = 20 log₁₀(Ad/Ac)." },
  { q:"Colpitts oscillator uses:", options:["Two inductors, one capacitor","Two capacitors, one inductor","RC ladder network","Crystal"], answer:1, explanation:"Colpitts: tapped capacitor divider (two C's) + one inductor. Hartley uses two L's." },
  { q:"FWR efficiency is higher than HWR because:", options:["It uses more diodes","Both half-cycles of AC are utilized","It has smaller ripple factor","It uses center-tap transformer"], answer:1, explanation:"FWR: both positive and negative half-cycles are rectified → higher average output → higher efficiency." },
  { q:"N-type semiconductor is formed by adding:", options:["Trivalent impurities (acceptors)","Pentavalent impurities (donors)","Both types","No impurities"], answer:1, explanation:"N-type doping: pentavalent (5 valence electrons) donors like P, As, Sb donate electrons." },
  { q:"Small signal model (hybrid-π) of BJT has transconductance gm = ?", options:["IC/VT","IB/VT","IE/VT","IC/VBE"], answer:0, explanation:"gm = IC/VT, where VT = thermal voltage ≈ 26 mV at room temperature." },
],

// ═══════════════════════════════════════════════════════════════════════
// SIGNALS & SYSTEMS — 40 questions
// ═══════════════════════════════════════════════════════════════════════
signals: [
  { q:"Signal x(t) = A·cos(ωt) is:", options:["Aperiodic and random","Periodic and deterministic","Aperiodic and deterministic","Random only"], answer:1, explanation:"Sinusoidal: periodic (period T=2π/ω) and deterministic." },
  { q:"Unit step function u(t):", options:["1 for t<0, 0 for t≥0","0 for all t","1 for t≥0, 0 for t<0","t for t≥0"], answer:2, explanation:"u(t) = 1 when t ≥ 0, 0 when t < 0." },
  { q:"Fourier series is applicable to:", options:["Aperiodic signals","Random signals","Periodic signals","Discrete signals only"], answer:2, explanation:"Fourier series decomposes periodic signals into harmonic components." },
  { q:"Laplace transform of unit step u(t):", options:["1","1/s²","s","1/s"], answer:3, explanation:"L{u(t)} = 1/s for Re(s) > 0." },
  { q:"Z-transform of unit impulse δ[n]:", options:["z","1/z","0","1"], answer:3, explanation:"Z{δ[n]} = 1 (by definition of Z-transform)." },
  { q:"Convolution in time domain is ___ in frequency domain:", options:["Addition","Division","Convolution","Multiplication"], answer:3, explanation:"Convolution theorem: time-domain convolution ↔ frequency-domain multiplication." },
  { q:"A causal system's output depends on:", options:["Future inputs only","Past and future inputs","Only present input","Present and past inputs only"], answer:3, explanation:"Causal: output depends only on present and past inputs, never future." },
  { q:"For BIBO stability, all poles must lie:", options:["On imaginary axis","In right half s-plane","In left half s-plane","At origin"], answer:2, explanation:"Stability: all poles in left half s-plane (negative real parts)." },
  { q:"Nyquist minimum sampling rate:", options:["Equal to fmax","Greater than fmax","At least 2 × fmax","Half of fmax"], answer:2, explanation:"fs ≥ 2fmax (Nyquist rate). Below this → aliasing." },
  { q:"Fourier transform of δ(t):", options:["0","Infinity","1","jω"], answer:2, explanation:"F{δ(t)} = 1 (uniform spectrum across all frequencies)." },
  { q:"Impulse response of LTI system:", options:["x(t)","y(t)","h(t)","f(t)"], answer:2, explanation:"h(t) = output when input = δ(t). Fully characterises the LTI system." },
  { q:"Transfer function H(s):", options:["Input/Output in Laplace domain","Input Laplace","Y(s)/X(s)","Inverse Laplace of output"], answer:2, explanation:"H(s) = Y(s)/X(s) with all initial conditions zero." },
  { q:"Gibbs phenomenon occurs in Fourier series of:", options:["Smooth signals","Periodic signals with discontinuities","Aperiodic signals","DC signals only"], answer:1, explanation:"Gibbs: overshoot (~9%) near jump discontinuities when truncating Fourier series." },
  { q:"Z-transform of x[n−k]:", options:["z^k·X(z)","X(z)/z^k","z^(−k)·X(z)","k·X(z)"], answer:2, explanation:"Time delay property: Z{x[n−k]} = z^(−k)·X(z)." },
  { q:"ROC of Z-transform for causal sequence:", options:["|z| < r","|z| = r","|z| > r","Entire z-plane"], answer:2, explanation:"Causal sequence: ROC is |z| > r (outside the outermost pole)." },
  { q:"Energy of x(t) = A·rect(t/T):", options:["A²/T","A²T","A/T","2A²T"], answer:1, explanation:"E = ∫|x(t)|²dt = A² × T." },
  { q:"Even signal x(t) satisfies:", options:["x(t) = −x(−t)","x(t) = x(−t)","x(t) = jx(−t)","x(t) = 0"], answer:1, explanation:"Even: x(t) = x(−t). Odd: x(t) = −x(−t)." },
  { q:"Aliasing occurs when:", options:["fs > 2fmax","fs = 2fmax","fs < 2fmax","fs = fmax"], answer:2, explanation:"Aliasing: sampling below Nyquist rate causes frequency-domain overlap." },
  { q:"System with memory depends on:", options:["Only present input","Only future inputs","Past or future inputs (not only present)","None of these"], answer:2, explanation:"Memory system: output depends on past (or future for non-causal) inputs." },
  { q:"Laplace transform of e^(−at)·u(t):", options:["1/(s−a)","1/(s+a)","s/(s+a)","a/(s+a)"], answer:1, explanation:"L{e^(−at)u(t)} = 1/(s+a), ROC: Re(s) > −a." },
  // --- new questions ---
  { q:"Parseval's theorem for energy signals:", options:["Time-domain energy = frequency-domain energy","Power = bandwidth","Energy = amplitude²","Bandwidth × power = constant"], answer:0, explanation:"Parseval: ∫|x(t)|²dt = (1/2π)∫|X(ω)|²dω. Total energy same in both domains." },
  { q:"A system is time-invariant if:", options:["Output changes with input amplitude","Time shift in input causes same time shift in output","It has zero initial conditions","All coefficients are constant and zero"], answer:1, explanation:"TI: x(t) → y(t) implies x(t−t₀) → y(t−t₀) for any t₀." },
  { q:"Laplace transform of t·e^(−at)·u(t):", options:["1/(s+a)²","1/(s+a)","s/(s+a)²","a/(s+a)²"], answer:0, explanation:"L{t·e^(−at)u(t)} = 1/(s+a)². Multiplication by t ↔ differentiation in s-domain." },
  { q:"LTI system output y(t) = ?", options:["x(t) × h(t)","x(t) + h(t)","x(t) * h(t) (convolution)","x(t) / h(t)"], answer:2, explanation:"y(t) = x(t) * h(t) (convolution with impulse response)." },
  { q:"Initial value theorem: lim(t→0+) x(t) = ?", options:["lim(s→0) X(s)","lim(s→∞) sX(s)","lim(s→0) sX(s)","lim(s→∞) X(s)"], answer:1, explanation:"Initial value: x(0+) = lim(s→∞) s·X(s)." },
  { q:"Final value theorem: lim(t→∞) x(t) = ?", options:["lim(s→∞) sX(s)","lim(s→0) sX(s)","lim(s→0) X(s)","lim(s→∞) X(s)"], answer:1, explanation:"Final value: x(∞) = lim(s→0) s·X(s) (valid when x(∞) exists)." },
  { q:"Z-transform: Z⁻¹{z/(z−a)} for causal sequence:", options:["a^n·u[n]","a^(n−1)·u[n]","n·a^n·u[n]","a^(−n)·u[n]"], answer:0, explanation:"Z⁻¹{z/(z−a)} = a^n·u[n] for |z| > |a|." },
  { q:"Fourier transform of cos(ω₀t):", options:["π[δ(ω−ω₀)+δ(ω+ω₀)]","2πδ(ω−ω₀)","j/ω","1/(jω+ω₀)"], answer:0, explanation:"F{cos(ω₀t)} = π[δ(ω−ω₀)+δ(ω+ω₀)] — two impulses in frequency domain." },
  { q:"N-point DFT of a sequence gives:", options:["N/2 components","2N components","N complex frequency components","N² components"], answer:2, explanation:"N-point DFT produces N complex frequency coefficients at equally spaced frequencies." },
  { q:"Discrete-time sinusoid x[n] = cos(Ωn) is periodic only when:", options:["Ω is any real number","Ω/2π is rational","Ω = 2π","Ω < π"], answer:1, explanation:"Discrete sinusoid is periodic only when Ω/(2π) = p/q (rational number)." },
  { q:"System y(t) = x(2t) is:", options:["Time-invariant","Non-causal and time-varying","Causal and time-invariant","Non-linear"], answer:1, explanation:"Time compression y(t) = x(2t): time-varying (input at 2t depends on future), non-causal for causal x(t)." },
  { q:"Cross-correlation between two signals measures:", options:["Frequency content","Similarity and time shift between signals","Convolution","Energy"], answer:1, explanation:"Cross-correlation: measures similarity and lag between two different signals." },
  { q:"A system is linear if it satisfies:", options:["Only superposition","Only homogeneity","Both superposition and homogeneity (linearity)","Only causality"], answer:2, explanation:"Linearity = superposition (additivity) + homogeneity (scaling)." },
  { q:"The period of signal x(t) = sin(3πt) + cos(4πt) is:", options:["1/3 s","1/2 s","2 s","1 s"], answer:2, explanation:"T1 = 2/3, T2 = 1/2. LCM(2/3, 1/2) = 2 s." },
  { q:"Signal x(t) = e^(−|t|) is:", options:["Causal and energy signal","Non-causal and power signal","Non-causal and energy signal","Periodic signal"], answer:2, explanation:"e^(−|t|) exists for t < 0 (non-causal) and has finite energy (energy signal)." },
  { q:"Inverse Laplace transform of 1/(s²+ω²):", options:["cos(ωt)·u(t)","e^(−ωt)·u(t)","sin(ωt)/ω·u(t)","sin(ωt)·u(t)"], answer:2, explanation:"L{sin(ωt)/ω} = 1/(s²+ω²). So L⁻¹{1/(s²+ω²)} = sin(ωt)/ω." },
  { q:"ROC of Laplace transform for stable causal system H(s):", options:["Includes the imaginary (jω) axis","Is in right half s-plane","Excludes all poles","Is a vertical strip only"], answer:0, explanation:"Stable + causal: all poles in LHP → ROC extends rightward and includes jω axis." },
  { q:"Sampling a signal at exactly the Nyquist rate (fs = 2fmax) without guard band causes:", options:["Perfect reconstruction always","Aliasing unless signal is band-limited exactly","No effect","Oversampling"], answer:1, explanation:"Sampling at exactly 2fmax is theoretically sufficient but impractical — requires ideal brick-wall filter." },
  { q:"Time-bandwidth product of a signal (uncertainty principle) means:", options:["Short duration signal has narrow bandwidth","Long duration signal has narrow bandwidth","A signal cannot have arbitrary narrow duration and bandwidth simultaneously","Duration equals bandwidth"], answer:2, explanation:"Uncertainty principle: Δt·Δf ≥ 1/(4π). Shorter pulses → wider bandwidth and vice versa." },
  { q:"A system with impulse response h(t) = u(t) is:", options:["Non-causal, unstable","Causal but not BIBO stable","Causal and stable","Memoryless"], answer:1, explanation:"h(t) = u(t): causal (h(t)=0 for t<0) but NOT stable — ∫|h(t)|dt = ∞." },
],

// ═══════════════════════════════════════════════════════════════════════
// CONTROL SYSTEMS — 35 questions
// ═══════════════════════════════════════════════════════════════════════
control: [
  { q:"Transfer function of a system:", options:["Input/Output in time domain","Y(s)/X(s) with zero initial conditions","Ratio of poles to zeros","Gain only"], answer:1, explanation:"H(s) = Y(s)/X(s) with all initial conditions zero." },
  { q:"BIBO stable system: all closed-loop poles must be in:", options:["Right half s-plane","Left half s-plane","On imaginary axis","At origin"], answer:1, explanation:"Stable: all poles have negative real parts (left half s-plane)." },
  { q:"Type 1 system with unit ramp input, steady-state error:", options:["Zero","Finite (1/Kv)","Infinity","1/Kp"], answer:1, explanation:"Type 1 + ramp → ess = 1/Kv." },
  { q:"Routh-Hurwitz stability: system stable when first column elements:", options:["Negative","Zero","All positive (same sign)","Complex"], answer:2, explanation:"All positive elements in first column → stable. Sign changes = number of RHP poles." },
  { q:"Number of branches in root locus equals:", options:["Number of zeros","Poles minus zeros","Number of open-loop poles","Gain K"], answer:2, explanation:"Root locus branches = number of open-loop poles." },
  { q:"Phase margin measured at:", options:["Phase crossover frequency","Gain crossover frequency (|G|=1)","Natural frequency","Resonant frequency"], answer:1, explanation:"PM = 180° + ∠G(jω) at gain crossover where |G(jω)| = 1 (0 dB)." },
  { q:"Gain margin is reciprocal of |G(jω)| at:", options:["Gain crossover","Phase crossover (∠G = −180°)","Zero frequency","Resonant frequency"], answer:1, explanation:"GM = 1/|G(jωpc)| at phase crossover where phase = −180°." },
  { q:"Bode plot of integrator 1/s has slope:", options:["−40 dB/decade","−20 dB/decade","0 dB/decade","+20 dB/decade"], answer:1, explanation:"1/s: slope = −20 dB/decade, phase = −90° (constant)." },
  { q:"PD controller adds a ___ to open-loop TF:", options:["Pole at origin","Zero","Double pole","Integrator"], answer:1, explanation:"PD: C(s) = Kp + Kds = Kd(s + Kp/Kd) — adds a zero." },
  { q:"PI controller adds a ___ to open-loop TF:", options:["Zero","Pole at origin (integrator)","Double zero","RHP pole"], answer:1, explanation:"PI: C(s) = (Kps + Ki)/s — adds pole at origin and a zero." },
  { q:"Steady-state error to step for Type 0 system:", options:["Zero","1/(1+Kp)","1/Kv","Infinity"], answer:1, explanation:"ess = 1/(1+Kp) for Type 0 system with step input." },
  { q:"Nyquist criterion: closed-loop stable when Nyquist plot:", options:["Encircles −1+j0 clockwise","Does not encircle −1+j0 (for stable G)","Passes through origin","Has gain > 1"], answer:1, explanation:"For open-loop stable system (P=0): N=0, no encirclement of −1+j0 → stable." },
  { q:"ξ < 1 gives ___ response:", options:["Overdamped","Critically damped","Underdamped (oscillatory)","Unstable"], answer:2, explanation:"ξ < 1: underdamped. ξ = 1: critically damped. ξ > 1: overdamped." },
  { q:"In Mason's gain formula, non-touching loops are:", options:["Added together","Multiplied together","Subtracted","Ignored"], answer:1, explanation:"Mason's Δ = 1 − Σ(loops) + Σ(non-touching loop products) − ..." },
  { q:"Characteristic equation of a feedback system:", options:["G(s) = 0","1 + G(s)H(s) = 0","G(s)H(s) = 0","G(s) = H(s)"], answer:1, explanation:"Closed-loop poles: denominator = 1 + G(s)H(s) = 0." },
  // --- new questions ---
  { q:"Root locus starts at (K=0) and ends (K→∞) at:", options:["Zeros, poles","Poles, zeros","Origin, infinity","Infinity, origin"], answer:1, explanation:"Root locus: starts at open-loop poles (K=0), ends at open-loop zeros (K→∞)." },
  { q:"Derivative action D in PID control:", options:["Reduces steady-state error","Responds to rate of change of error (improves transient)","Eliminates steady-state offset","Reduces stability margin"], answer:1, explanation:"D-action: responds to de/dt — reduces overshoot and improves transient response." },
  { q:"Rise time decreases (faster response) when:", options:["Damping ratio increases","Natural frequency decreases","Natural frequency ωn increases","System order increases"], answer:2, explanation:"tr ≈ π/ωd. Higher ωn → shorter rise time." },
  { q:"%OS (percent overshoot) for 2nd order system depends on:", options:["Natural frequency only","Damping ratio ξ only","Both ξ and ωn","Gain K only"], answer:1, explanation:"%OS = e^(−πξ/√(1−ξ²)) × 100. Depends only on ξ." },
  { q:"System with poles at s = −2±j3 has ωn = ?", options:["2","3","√13","5"], answer:2, explanation:"ωn = √(σ²+ωd²) = √(4+9) = √13." },
  { q:"Good stability margins require:", options:["GM < 0 dB and PM < 0°","GM > 6 dB and PM > 30°","GM = 0 dB","GM negative, PM positive"], answer:1, explanation:"Typical design: GM > 6 dB, PM between 30–60°." },
  { q:"Type 2 system with step input: ess = ?", options:["1/(1+Kp)","1/Kv","Zero","Infinite"], answer:2, explanation:"Type 2 with step: ess = 0. Type 2 with parabola: ess = 1/Ka." },
  { q:"Resonance peak Mr = 1/(2ξ√(1−ξ²)) indicates:", options:["System bandwidth","Lower Mr = higher ξ = better damping","Natural frequency","Gain margin"], answer:1, explanation:"Higher Mr = lower damping = more oscillatory. Design typically targets Mr ≤ 1.3." },
  { q:"Controllability of a system means:", options:["State can be driven from any initial state to any desired state","Output tracks reference","System is stable","Poles are in LHP"], answer:0, explanation:"Controllability: can all states be driven to desired values by the input?" },
  { q:"Settling time (2% criterion) for 2nd order system ≈", options:["π/ωd","1/(ξωn)","4/(ξωn)","2π/ωn"], answer:2, explanation:"ts ≈ 4/(ξωn) for 2% criterion." },
  { q:"A marginally stable system has poles on:", options:["Left half s-plane","Right half s-plane","Imaginary axis exactly","Origin only"], answer:2, explanation:"Marginally stable: poles on imaginary axis → sustained oscillation (neither growing nor decaying)." },
  { q:"Lead compensator in frequency domain:", options:["Reduces phase","Adds phase lag","Adds phase lead — improves speed and PM","Reduces bandwidth"], answer:2, explanation:"Lead compensator: adds positive phase, improves phase margin, speeds up transient response." },
  { q:"Type 0 system with ramp input: ess = ?", options:["0","1/Kp","1/Kv","Infinite"], answer:3, explanation:"Type 0: Kv = 0. ess to ramp = 1/Kv = ∞." },
  { q:"PID combines effects of:", options:["Proportional + Integral only","Derivative + Integral only","Proportional, Integral, and Derivative","Gain and phase only"], answer:2, explanation:"PID = P (reduces error) + I (eliminates steady-state error) + D (improves transient)." },
  { q:"The angle condition for root locus (negative feedback):", options:["∠G(s)H(s) = 0°","∠G(s)H(s) = ±(2k+1)×180°","∠G(s)H(s) = 90°","∠G(s)H(s) = 360°"], answer:1, explanation:"Root locus angle condition: ∠G(s)H(s) = ±(2k+1)×180°, k = 0,1,2,..." },
  { q:"Break-away point on root locus satisfies:", options:["Two poles are adjacent","dK/ds = 0","Phase = −180°","Gain = 0 dB"], answer:1, explanation:"Break-away point: where root locus leaves real axis, found by setting dK/ds = 0." },
  { q:"Ziegler-Nichols method is used for:", options:["Designing Bode plots","Tuning PID controller parameters","Finding transfer function","Stability analysis"], answer:1, explanation:"Ziegler-Nichols: empirical method to set PID gains based on plant response characteristics." },
  { q:"Steady-state error for Type 0 system with parabolic input:", options:["Zero","1/Kp","1/Ka","Infinite"], answer:3, explanation:"Type 0: Ka = 0. ess to parabola = 1/Ka = ∞." },
  { q:"In a closed-loop system, sensitivity to plant gain changes is:", options:["Increased by feedback","Reduced by negative feedback (1/(1+GH))","Not affected","Equal to 1"], answer:1, explanation:"Sensitivity S = 1/(1+GH). Negative feedback reduces sensitivity to parameter variations." },
],

// ═══════════════════════════════════════════════════════════════════════
// COMMUNICATIONS — 40 questions
// ═══════════════════════════════════════════════════════════════════════
communications: [
  { q:"AM modulation index m =", options:["Ac/Am","Am/Ac","(Amax+Amin)/2","Amax×Amin"], answer:1, explanation:"m = Am/Ac. For distortion-free AM: 0 ≤ m ≤ 1." },
  { q:"AM bandwidth (single-tone modulation):", options:["fm","2fm","fm/2","4fm"], answer:1, explanation:"AM BW = 2fm (upper and lower sidebands, each fm from carrier)." },
  { q:"Total AM power: Pt = ?", options:["Pc(1+m)","Pc(1+m²/2)","Pc×m²","Pc/2"], answer:1, explanation:"Pt = Pc(1+m²/2). At m=1: Pt = 1.5Pc." },
  { q:"FM modulation index β =", options:["fm/Δf","Δf/fm","Ac/Am","2Δf/fm"], answer:1, explanation:"β = Δf/fm, where Δf = maximum frequency deviation." },
  { q:"FM bandwidth by Carson's rule:", options:["2Δf","2fm","2(Δf+fm)","Δf+fm"], answer:2, explanation:"BW = 2(Δf+fm) = 2fm(β+1)." },
  { q:"Shannon channel capacity: C =", options:["B×SNR","B log₂(1+SNR)","log₂(1+SNR)","B×log₂(SNR)"], answer:1, explanation:"Shannon: C = B log₂(1+S/N) bits/second." },
  { q:"PCM bit rate with sampling rate fs and n bits:", options:["fs+n","fs×n","fs/n","n/fs"], answer:1, explanation:"Bit rate = fs × n bps." },
  { q:"FM noise performance better than AM when:", options:["β < 1","β = 1","β > 1","Always worse"], answer:2, explanation:"FM with large β has superior SNR improvement ∝ 3β²(β+1)." },
  { q:"QPSK transmits ___ bits per symbol:", options:["1","2","3","4"], answer:1, explanation:"QPSK: 4 phase states → log₂(4) = 2 bits per symbol." },
  { q:"In AM, which component carries information?", options:["Carrier","Upper sideband","Lower sideband","Both sidebands"], answer:3, explanation:"Both sidebands carry identical information. Carrier carries no information." },
  { q:"Superheterodyne receiver uses:", options:["RF amplifier alone","IF filter alone","Mixer + local oscillator to produce fixed IF","Demodulator only"], answer:2, explanation:"Superhet: mixes RF with LO to produce fixed IF frequency for better selectivity." },
  { q:"Image frequency in AM superheterodyne:", options:["fRF−fIF","fRF+2fIF","fRF+fIF","2fIF"], answer:1, explanation:"Image freq = fRF + 2fIF (also mixes to IF frequency)." },
  { q:"PCM steps in correct order:", options:["Sample→Quantize→Encode","Encode→Sample→Quantize","Quantize→Sample→Encode","Sample→Encode→Quantize"], answer:0, explanation:"PCM: Sampling → Quantization → Encoding." },
  { q:"VSB modulation is used in:", options:["Radio FM","Television broadcasting","GPS","Satellite phones"], answer:1, explanation:"VSB used in TV — compromise between DSB (wide BW) and SSB (difficult filtering)." },
  { q:"FSK stands for:", options:["Frequency stays constant","Frequency Shift Keying (frequency varies with data)","Phase varies with data","Amplitude varies with data"], answer:1, explanation:"FSK: different frequencies represent binary 0 and 1." },
  // --- new questions ---
  { q:"SSB-SC transmitted power compared to DSB-SC:", options:["Same","Double","Half","One-fourth"], answer:2, explanation:"SSB transmits only one sideband → half the power of DSB-SC." },
  { q:"In 8-PSK, bits per symbol:", options:["2","3","4","8"], answer:1, explanation:"8-PSK: 8 phase states → log₂(8) = 3 bits per symbol." },
  { q:"Entropy H is maximum when all messages:", options:["Have equal probability","One message has probability 1","Are binary","Have minimum bandwidth"], answer:0, explanation:"Maximum entropy when all symbols are equally probable (maximum uncertainty)." },
  { q:"Delta modulation suffers from:", options:["ISI","Slope overload and granular noise","Phase distortion","Frequency drift"], answer:1, explanation:"DM: slope overload when signal changes too fast; granular noise when signal is nearly constant." },
  { q:"Bits required to quantize to 256 levels:", options:["6","7","8","9"], answer:2, explanation:"2ⁿ = 256 → n = 8 bits." },
  { q:"De-emphasis in FM is used to:", options:["Increase high-freq deviation","Reduce high-freq noise after demodulation","Increase bandwidth","Correct phase distortion"], answer:1, explanation:"Pre-emphasis at Tx boosts high-freq; de-emphasis at Rx restores and reduces high-freq noise." },
  { q:"IF frequency of standard AM superheterodyne receiver:", options:["455 Hz","455 kHz","4.55 MHz","45 MHz"], answer:1, explanation:"Standard AM receiver IF = 455 kHz. FM receiver IF = 10.7 MHz." },
  { q:"Wideband FM has:", options:["β < 1","β = 1","β >> 1","β = 0"], answer:2, explanation:"WBFM: β >> 1. NBFM: β < 0.3. Commercial FM: β ≈ 5." },
  { q:"AM carrier frequency component:", options:["Carries information","Wastes power (contains no information)","Is the sideband","Equals the modulating signal"], answer:1, explanation:"AM carrier carries no information — sidebands carry info. Carrier wastes ≥ 66% power when m=1." },
  { q:"Manchester encoding has:", options:["DC component","No DC component (self-clocking)","Two voltage levels only","No transitions"], answer:1, explanation:"Manchester: mid-bit transition ensures no DC component — self-clocking." },
  { q:"Minimum bandwidth for ISI-free transmission (Nyquist):", options:["= bit rate","= bit rate / 2","= 2 × bit rate","= bit rate × log₂M"], answer:1, explanation:"Nyquist minimum BW = Rs/2 (for binary, Rb/2)." },
  { q:"QAM modulates using:", options:["Frequency only","Phase only","Both amplitude and phase","Frequency and amplitude"], answer:2, explanation:"QAM: Quadrature Amplitude Modulation — varies both amplitude and phase." },
  { q:"SNR advantage of FM over AM ≈", options:["3β²","3β²(β+1)","β²","3β"], answer:1, explanation:"FM SNR improvement over AM ≈ 3β²(β+1) for large β." },
  { q:"Quantization noise power is proportional to:", options:["N (quantization levels)","1/N²","N²","log₂N"], answer:1, explanation:"Quantization noise ∝ (step size)² ∝ 1/N². More levels → less quantization noise." },
  { q:"Matched filter maximises:", options:["Bandwidth","SNR at the sampling instant","Amplitude","Frequency deviation"], answer:1, explanation:"Matched filter: maximises instantaneous SNR at the decision/sampling instant." },
  { q:"Eye diagram is used to assess:", options:["AM modulation quality","ISI (Inter-Symbol Interference) in digital communication","FM deviation","Noise figure"], answer:1, explanation:"Eye diagram: superimposed bit waveforms. Wide open eye = low ISI; closed = high ISI." },
  { q:"Hamming (7,4) code can correct:", options:["0 errors","1 bit error","2 bit errors","3 bit errors"], answer:1, explanation:"Hamming (7,4): 4 data + 3 parity bits. Corrects 1-bit error, detects 2-bit errors." },
  { q:"Coherent detection requires:", options:["Only signal knowledge","Local carrier synchronised in phase and frequency with Tx","No carrier at receiver","Only envelope detection"], answer:1, explanation:"Coherent: receiver must generate a carrier in exact sync with the transmitted carrier." },
  { q:"OFDM combats multipath fading by:", options:["Using a single carrier","Converting to many parallel low-rate sub-carriers + cyclic prefix","Increasing power","Using directional antennas"], answer:1, explanation:"OFDM: splits data across many narrow sub-bands. Each sees flat fading; CP eliminates ISI." },
  { q:"BER for BPSK in AWGN = ?", options:["Q(√(2Eb/N0))","Q(√(Eb/N0))","Q(2Eb/N0)","(1/2)e^(−Eb/N0)"], answer:0, explanation:"BER_BPSK = Q(√(2Eb/N0))." },
  { q:"DPCM compared to PCM:", options:["Uses more bits","Encodes differences → lower bit rate","Has higher noise","No quantization"], answer:1, explanation:"DPCM: encodes sample differences (smaller values) → fewer bits required for same quality." },
  { q:"8-QAM constellation has:", options:["8 amplitude levels","8 phase states","Combination of 2 amplitudes and 4 phases (or similar)","8 frequency shifts"], answer:2, explanation:"8-QAM: 8 points on constellation using amplitude and phase combinations." },
  { q:"Nyquist rate for a signal with bandwidth B Hz is:", options:["B samples/s","2B samples/s","B/2 samples/s","4B samples/s"], answer:1, explanation:"Nyquist: minimum sampling rate = 2B samples per second to avoid aliasing." },
],

// ═══════════════════════════════════════════════════════════════════════
// EM THEORY — 25 questions (NEW)
// ═══════════════════════════════════════════════════════════════════════
emtheory: [
  { q:"Gauss's law: flux through a closed surface = ?", options:["Total charge enclosed × ε₀","Total charge enclosed / ε₀","Surface area × E","Volume × ρ"], answer:1, explanation:"Gauss: ∮E·dA = Qenc/ε₀." },
  { q:"Coulomb's law: force between Q1 and Q2 separated by d:", options:["F = Q1Q2/(4πε₀d)","F = Q1Q2/(4πε₀d²)","F = Q1Q2d/(4πε₀)","F = 4πε₀Q1Q2/d²"], answer:1, explanation:"F = Q1Q2/(4πε₀d²). Inverse square law." },
  { q:"Electric field E and potential V are related by:", options:["E = ∇V","E = −∇V","V = ∇E","E = V/distance only"], answer:1, explanation:"E = −∇V. Field points in direction of decreasing potential." },
  { q:"Ampere's law (modified by Maxwell) includes:", options:["Only conduction current","Conduction + displacement current (ε₀ dΦE/dt)","Magnetic current","Current density only"], answer:1, explanation:"Modified Ampere: ∮H·dl = I_enc + ε₀·dΦE/dt (Maxwell added displacement current)." },
  { q:"Faraday's law of electromagnetic induction:", options:["EMF = ΦB/t","EMF = −dΦB/dt","∮E·dl = 0","∮H·dl = 0"], answer:1, explanation:"Faraday: EMF = −dΦB/dt. Negative sign (Lenz's law) opposes the change." },
  { q:"EM wave velocity in free space:", options:["Depends on frequency","3×10⁸ m/s (speed of light)","Speed of sound","c/√εr"], answer:1, explanation:"EM waves in vacuum: v = 1/√(μ₀ε₀) = 3×10⁸ m/s." },
  { q:"Intrinsic impedance of free space η₀ ≈", options:["50 Ω","75 Ω","377 Ω (= 120π Ω)","600 Ω"], answer:2, explanation:"η₀ = √(μ₀/ε₀) = 120π ≈ 377 Ω." },
  { q:"Skin depth δ in a conductor:", options:["√(2ρ/ωμ) = √(2/ωμσ)","√(ωμσ/2)","1/(ωμσ)","ωμσ"], answer:0, explanation:"δ = √(2/ωμσ). At higher frequency, current confined to thin surface layer." },
  { q:"For plane wave in lossless medium, E, H, and propagation direction are:", options:["All parallel","All perpendicular to each other (TEM)","E and H parallel, perpendicular to k","H parallel to k"], answer:1, explanation:"TEM: E, H, and direction of propagation k are mutually perpendicular." },
  { q:"SWR (Standing Wave Ratio) for perfect impedance match:", options:["0","1 (no reflections)","Infinite","2"], answer:1, explanation:"Perfect match: Γ = 0, SWR = (1+0)/(1−0) = 1." },
  { q:"Characteristic impedance Z₀ of a transmission line:", options:["Depends on load ZL","Z₀ = √(L'/C') (per-unit-length L and C)","Depends on line length","Depends on applied voltage"], answer:1, explanation:"Z₀ = √(L'/C') — intrinsic property of the line, independent of length or load." },
  { q:"Reflection coefficient Γ at load ZL:", options:["ZL/(ZL+Z₀)","(ZL−Z₀)/(ZL+Z₀)","Z₀/ZL","(Z₀−ZL)/Z₀"], answer:1, explanation:"Γ = (ZL−Z₀)/(ZL+Z₀). Perfect match: ZL=Z₀ → Γ = 0." },
  { q:"Directivity of an isotropic antenna:", options:["0 dBi = 1 (equal in all directions)","3 dBi","10 dBi","Depends on frequency"], answer:0, explanation:"Isotropic: D = 1 (0 dBi). All practical antennas have D ≥ 1." },
  { q:"Maxwell's equation ∇·B = 0 means:", options:["Magnetic monopoles exist","No magnetic monopoles — B lines are closed loops","B = 0 in free space","B is conservative"], answer:1, explanation:"∇·B = 0: no isolated magnetic poles exist. B field lines always form closed loops." },
  { q:"Poynting vector S = E × H represents:", options:["Charge density","Power per unit area (W/m²) in direction of wave travel","Magnetic flux","Electric potential"], answer:1, explanation:"Poynting vector: instantaneous power flow density of EM wave." },
  { q:"λ/4 transformer input impedance (given Z₀_t, ZL):", options:["ZL","Z₀_t²/ZL","ZL×Z₀_t","Z₀_t"], answer:1, explanation:"λ/4 transformer: Zin = Z₀_t²/ZL. Used to match load to source." },
  { q:"Skin effect causes resistance at high frequency to:", options:["Decrease","Remain constant","Increase (current crowds at surface)","Become reactive"], answer:2, explanation:"Skin effect: effective cross-section decreases → resistance increases with frequency." },
  { q:"Input impedance of a short-circuited λ/4 line:", options:["0 (short)","Infinite (open)","Z₀","Z₀/2"], answer:1, explanation:"λ/4 shorted line: Zin = jZ₀tan(π/2) → ∞ (behaves like open circuit)." },
  { q:"Group velocity vg = ?", options:["ω/β","dω/dβ","βω","ω/2π"], answer:1, explanation:"Group velocity: vg = dω/dβ. Phase velocity: vp = ω/β." },
  { q:"TE mode in rectangular waveguide has:", options:["No transverse E field","Ez = 0 (no longitudinal E)","Hz = 0 (no longitudinal H)","Both E and H transverse"], answer:1, explanation:"TE (Transverse Electric): Ez = 0, Hz ≠ 0." },
  { q:"Cutoff frequency of TE₁₀ mode (dominant, wide dimension a):", options:["c/(2a)","c/a","c/(4a)","2c/a"], answer:0, explanation:"fc(TE₁₀) = c/(2a). Lowest cutoff frequency among all modes." },
  { q:"Boundary condition for tangential component of E at interface:", options:["Et1 = 0","Et1 = Et2 (continuous)","Et1 = ε2·Et2","Discontinuous"], answer:1, explanation:"Tangential E is continuous at any interface: Et1 = Et2." },
  { q:"Biot-Savart law is used to find:", options:["Electric field of a charge","Magnetic field of a current element","EM wave velocity","Transmission line impedance"], answer:1, explanation:"Biot-Savart: dH = I dl × â_r/(4πr²) — fundamental law for magnetic field due to current." },
  { q:"Brewster's angle occurs when:", options:["Total reflection happens","No reflection for TM (parallel) polarised wave","Maximum absorption","Diffraction begins"], answer:1, explanation:"Brewster angle: reflected wave vanishes for TM polarisation. tan(θ_B) = ε₂/ε₁." },
  { q:"For a λ/2 dipole antenna, radiation resistance is approximately:", options:["36.5 Ω","73 Ω","120π Ω","50 Ω"], answer:1, explanation:"Half-wave dipole: Rrad ≈ 73 Ω (in free space)." },
],

// ═══════════════════════════════════════════════════════════════════════
// ENGINEERING MATHEMATICS — 25 questions (NEW)
// ═══════════════════════════════════════════════════════════════════════
engineering_maths: [
  { q:"Determinant of matrix [[2,1],[4,3]]:", options:["2","6","10","8"], answer:0, explanation:"det = 2×3 − 1×4 = 6 − 4 = 2." },
  { q:"Eigenvalues of upper triangular matrix [[3,1],[0,2]]:", options:["3 and 1","2 and 1","3 and 2","0 and 2"], answer:2, explanation:"Upper triangular: eigenvalues are the diagonal elements = 3 and 2." },
  { q:"Rank of matrix [[1,2],[2,4]]:", options:["2","1","0","3"], answer:1, explanation:"Row 2 = 2 × Row 1 → linearly dependent. Rank = 1." },
  { q:"d/dx[sin(x)] =", options:["−cos(x)","cos(x)","−sin(x)","tan(x)"], answer:1, explanation:"d/dx[sin x] = cos x." },
  { q:"∫e^x dx =", options:["e^x/x","e^x + C","xe^x + C","e^(x+1)/(x+1) + C"], answer:1, explanation:"∫e^x dx = e^x + C." },
  { q:"Power rule: d/dx(x^n) = ?", options:["nx^n","nx^(n−1)","x^(n+1)/(n+1)","n/x"], answer:1, explanation:"Power rule: d/dx(x^n) = nx^(n−1)." },
  { q:"P(A∪B) = P(A)+P(B) when:", options:["A and B are dependent","A and B are mutually exclusive","A is subset of B","A = B"], answer:1, explanation:"P(A∪B) = P(A)+P(B) only when A and B are mutually exclusive (P(A∩B)=0)." },
  { q:"Normal distribution is symmetric about:", options:["Zero","The mean μ","The variance σ²","The standard deviation σ"], answer:1, explanation:"Normal distribution: symmetric bell curve centred at mean μ." },
  { q:"Solution of dy/dx = ky:", options:["y = Ce^(kx)","y = kx+C","y = Cx^k","y = C·sin(kx)"], answer:0, explanation:"dy/dx = ky → y = Ce^(kx)." },
  { q:"Bayes' theorem: P(A|B) = ?", options:["P(B|A)×P(A)/P(B)","P(A)×P(B)","P(A∩B)/P(A)","P(B)/P(A)"], answer:0, explanation:"P(A|B) = P(B|A)·P(A)/P(B)." },
  { q:"Trace of a matrix equals:", options:["Sum of all elements","Sum of diagonal elements","Product of diagonal elements","Determinant"], answer:1, explanation:"Trace = sum of main diagonal elements = sum of all eigenvalues." },
  { q:"Unique solution to Ax = b exists when:", options:["det(A) = 0","det(A) ≠ 0 (A is non-singular)","Rank(A) < n","A is singular"], answer:1, explanation:"Unique solution exists when A is non-singular (invertible)." },
  { q:"L'Hôpital's rule applies to:", options:["Finite/finite","0/0 or ∞/∞ indeterminate forms","0/∞","1/0"], answer:1, explanation:"L'Hôpital: differentiate numerator and denominator for 0/0 or ∞/∞ forms." },
  { q:"Mean of binomial distribution B(n,p):", options:["np(1−p)","np","p/n","n/p"], answer:1, explanation:"Binomial: mean = np, variance = np(1−p)." },
  { q:"Gradient ∇f at a point gives:", options:["Curl of f","Direction of maximum increase of f","Laplacian of f","Volume integral"], answer:1, explanation:"∇f: direction and magnitude of steepest ascent of scalar field f." },
  { q:"Cayley-Hamilton theorem states:", options:["Matrix satisfies its own characteristic equation","Eigenvalues equal trace","det = product of eigenvalues","Matrix power = eigenvalue power"], answer:0, explanation:"Cayley-Hamilton: substitute matrix into its characteristic polynomial → zero matrix." },
  { q:"Laplace transform converts ODEs into:", options:["Integral equations","Algebraic equations in s-domain","Difference equations","PDEs"], answer:1, explanation:"Laplace: converts linear ODEs with constant coefficients into algebraic equations." },
  { q:"∇²φ = 0 is called ___:", options:["Heat equation","Wave equation","Laplace's equation","Poisson's equation"], answer:2, explanation:"∇²φ = 0 is Laplace's equation. ∇²φ = ρ/ε is Poisson's equation." },
  { q:"Probability at least one head in 3 fair coin tosses:", options:["3/8","1/2","7/8","1/4"], answer:2, explanation:"P(at least one H) = 1 − P(no heads) = 1 − (1/2)³ = 7/8." },
  { q:"Taylor series of e^x around x = 0:", options:["1−x+x²/2!−...","1+x+x²/2!+x³/3!+...","x+x²/2+x³/3+...","1+2x+3x²+..."], answer:1, explanation:"e^x = Σ(x^n/n!) = 1 + x + x²/2! + x³/3! + ..." },
  { q:"Order of a differential equation is:", options:["Power of dependent variable","Highest derivative in equation","Number of variables","Degree"], answer:1, explanation:"Order = highest derivative present. Degree = power of that highest derivative." },
  { q:"For independent random variables X, Y: Var(X+Y) = ?", options:["Var(X)×Var(Y)","Var(X)+Var(Y)","Var(X)−Var(Y)","[Var(X)+Var(Y)]²"], answer:1, explanation:"Independence: Var(X+Y) = Var(X) + Var(Y)." },
  { q:"Poisson distribution models:", options:["Continuous variables","Rare events in a fixed interval","Normal processes","Binary outcomes only"], answer:1, explanation:"Poisson: count of rare independent events in a fixed time/space interval." },
  { q:"d/dx[ln(x)] = ?", options:["1/x²","x","1/x","ln(x)/x"], answer:2, explanation:"d/dx[ln(x)] = 1/x for x > 0." },
  { q:"Partial differential equation has:", options:["Ordinary derivatives only","Partial derivatives with respect to 2+ independent variables","Only time as variable","No derivatives"], answer:1, explanation:"PDE: derivatives with respect to two or more independent variables (e.g., space and time)." },
],

// ═══════════════════════════════════════════════════════════════════════
// APTITUDE (Paper I — Numerical) — 40 questions
// ═══════════════════════════════════════════════════════════════════════
aptitude: [
  { q:"20% of a number is 80. The number is:", options:["160","400","420","480"], answer:1, explanation:"x × 20/100 = 80 → x = 400." },
  { q:"Train travels 300 km in 5 hours. Speed (km/h):", options:["50","55","60","65"], answer:2, explanation:"Speed = 300/5 = 60 km/h." },
  { q:"A:B = 3:4, B:C = 2:3. A:C = ?", options:["1:2","2:3","3:8","1:3"], answer:0, explanation:"A:B:C = 6:8:12 → A:C = 1:2." },
  { q:"15% of 240 = ?", options:["32","34","36","38"], answer:2, explanation:"240 × 15/100 = 36." },
  { q:"CP = Rs.200, SP = Rs.250. Profit % = ?", options:["20%","25%","30%","50%"], answer:1, explanation:"Profit = 50, Profit% = (50/200)×100 = 25%." },
  { q:"6 workers do job in 10 days. 10 workers do it in:", options:["8 days","6 days","4 days","5 days"], answer:1, explanation:"Work = 6×10 = 60. Time = 60/10 = 6 days." },
  { q:"SI on Rs.5000 at 8% p.a. for 3 years:", options:["Rs.1200","Rs.1400","Rs.1000","Rs.1600"], answer:0, explanation:"SI = 5000×8×3/100 = Rs.1200." },
  { q:"Next in series: 2, 6, 12, 20, 30, ___", options:["38","40","42","44"], answer:2, explanation:"Differences: 4,6,8,10,12 → 30+12 = 42." },
  { q:"40% are boys. 30 girls are present. Total students:", options:["40","45","50","55"], answer:2, explanation:"Girls = 60% = 30 → total = 50." },
  { q:"What is 35% of 600?", options:["180","200","210","225"], answer:2, explanation:"600 × 35/100 = 210." },
  // --- new aptitude questions ---
  { q:"CI on Rs.10000 at 10% p.a. for 2 years:", options:["Rs.2000","Rs.2100","Rs.1900","Rs.2200"], answer:1, explanation:"CI = P[(1+r)^n − 1] = 10000[(1.1)² − 1] = 10000 × 0.21 = Rs.2100." },
  { q:"A car travels 60 km at 40 km/h, then 60 km at 60 km/h. Average speed:", options:["48 km/h","50 km/h","52 km/h","54 km/h"], answer:0, explanation:"Avg speed = 2×40×60/(40+60) = 4800/100 = 48 km/h (harmonic mean)." },
  { q:"Profit is 20% on CP. SP is Rs.240. CP = ?", options:["Rs.180","Rs.200","Rs.220","Rs.250"], answer:1, explanation:"SP = CP × 1.2 → CP = 240/1.2 = Rs.200." },
  { q:"A pipe fills a tank in 6 hrs. Another empties it in 8 hrs. Together (filling):", options:["24 hrs","16 hrs","14 hrs","20 hrs"], answer:0, explanation:"Net rate = 1/6 − 1/8 = 1/24. Time = 24 hrs." },
  { q:"Next prime number after 23:", options:["25","27","29","31"], answer:2, explanation:"25=5², 27=3³ — not prime. 29 is prime." },
  { q:"If 5x − 2 = 3x + 8, then x = ?", options:["3","4","5","6"], answer:2, explanation:"5x − 3x = 8 + 2 → 2x = 10 → x = 5." },
  { q:"A number when multiplied by 5 gives 125. The number:", options:["20","25","30","15"], answer:1, explanation:"x × 5 = 125 → x = 25." },
  { q:"Find the missing number: 4, 9, 16, 25, ___", options:["30","36","40","49"], answer:1, explanation:"Perfect squares: 2², 3², 4², 5², 6² = 36." },
  { q:"If A is 25% more than B, B is ___% less than A:", options:["20%","25%","15%","30%"], answer:0, explanation:"A = 1.25B. B/A = 1/1.25 = 0.8. B is 20% less than A." },
  { q:"LCM of 12 and 18:", options:["6","36","72","24"], answer:1, explanation:"LCM(12,18) = 36." },
  { q:"HCF of 24 and 36:", options:["6","8","12","18"], answer:2, explanation:"HCF(24,36) = 12." },
  { q:"Rs.6000 invested at 5% p.a. SI for 3 years. Amount = ?", options:["Rs.6900","Rs.7000","Rs.7200","Rs.6500"], answer:0, explanation:"SI = 6000×5×3/100 = 900. Amount = 6000+900 = Rs.6900." },
  { q:"Average of 5 consecutive even numbers starting from 4:", options:["8","10","12","14"], answer:2, explanation:"4,6,8,10,12. Average = (4+12)/2 = 8. Wait: sum=40, avg=8." },
  { q:"Average of 5 numbers is 10. One number 15 is replaced by 25. New average:", options:["10","11","12","13"], answer:2, explanation:"Total was 50. New total = 50 − 15 + 25 = 60. New avg = 60/5 = 12." },
  { q:"A can do a work in 12 days, B in 18 days. Together:", options:["6.5 days","7.2 days","7.5 days","8 days"], answer:1, explanation:"Rate = 1/12+1/18 = 5/36. Time = 36/5 = 7.2 days." },
  { q:"Discount of 20% on an item priced Rs.500. SP = ?", options:["Rs.350","Rs.380","Rs.400","Rs.420"], answer:2, explanation:"SP = 500 × (1−0.20) = 500 × 0.80 = Rs.400." },
  { q:"Train 100 m long at 60 km/h passes a pole in:", options:["4 s","6 s","8 s","10 s"], answer:1, explanation:"Speed = 60 km/h = 100/6 m/s. Time = 100/(100/6) = 6 s." },
  { q:"Two numbers sum = 40, difference = 10. The numbers:", options:["20 and 20","25 and 15","30 and 10","22 and 18"], answer:1, explanation:"x+y=40, x−y=10 → x=25, y=15." },
  { q:"Find x: (x/5) + 3 = 7:", options:["10","15","20","25"], answer:2, explanation:"x/5 = 4 → x = 20." },
  { q:"A man sells at 10% loss. Had he sold at Rs.60 more, he would have gained 5%. CP = ?", options:["Rs.360","Rs.400","Rs.450","Rs.500"], answer:1, explanation:"0.9×CP + 60 = 1.05×CP → 60 = 0.15×CP → CP = Rs.400." },
  { q:"In a triangle, two angles are 50° and 70°. Third angle:", options:["50°","60°","70°","80°"], answer:1, explanation:"Sum of angles = 180°. Third = 180−50−70 = 60°." },
  { q:"Speed of boat upstream = 10 km/h, downstream = 14 km/h. Speed of current:", options:["2 km/h","4 km/h","6 km/h","8 km/h"], answer:0, explanation:"Current = (downstream − upstream)/2 = (14−10)/2 = 2 km/h." },
  { q:"Percentage increase from 40 to 50:", options:["10%","20%","25%","30%"], answer:2, explanation:"Increase = 10. % = (10/40)×100 = 25%." },
  { q:"What fraction of 1 hour is 20 minutes?", options:["1/4","1/3","1/6","2/3"], answer:1, explanation:"20/60 = 1/3." },
  { q:"4! (4 factorial) =", options:["8","16","24","32"], answer:2, explanation:"4! = 4×3×2×1 = 24." },
  { q:"The sum 1+2+3+...+20 =", options:["180","190","200","210"], answer:3, explanation:"Sum = n(n+1)/2 = 20×21/2 = 210." },
  { q:"If A:B:C = 2:3:5, and total is 1000, B's share:", options:["200","300","500","400"], answer:1, explanation:"B's share = (3/10)×1000 = 300." },
  { q:"A discount of 10% and then 20% is equivalent to a single discount of:", options:["25%","28%","30%","27%"], answer:1, explanation:"Effective = 1−(0.9×0.8) = 1−0.72 = 0.28 = 28%." },
  { q:"Ratio of 35 minutes to 1 hour 25 minutes:", options:["7:13","7:17","35:85","7:19"], answer:1, explanation:"35 min : 85 min = 7:17." },
  { q:"The value of √144 + √25 =", options:["14","17","19","21"], answer:1, explanation:"√144 = 12, √25 = 5. Sum = 17." },
],

// ═══════════════════════════════════════════════════════════════════════
// REASONING (Paper I — Logical) — 25 questions (NEW)
// ═══════════════════════════════════════════════════════════════════════
reasoning: [
  { q:"Complete: 2, 4, 8, 16, ___", options:["18","24","32","30"], answer:2, explanation:"Each term doubles. 16×2 = 32." },
  { q:"Complete: 1, 4, 9, 16, 25, ___", options:["30","36","40","49"], answer:1, explanation:"Perfect squares: 1²,2²,...,5²,6² = 36." },
  { q:"Complete: 3, 6, 11, 18, 27, ___", options:["38","36","40","42"], answer:0, explanation:"Differences: 3,5,7,9,11 → 27+11 = 38." },
  { q:"If NORTH is coded as SOUTH in a mirror-direction system, EAST is coded as:", options:["WEST","NORTH","SOUTH","EAST"], answer:0, explanation:"Opposite direction: NORTH↔SOUTH, EAST↔WEST." },
  { q:"All dogs are animals. All animals have four legs. What follows?", options:["All four-legged things are dogs","All dogs have four legs","Animals are dogs","Dogs don't have legs"], answer:1, explanation:"Syllogism: dogs are animals (given) + animals have four legs → dogs have four legs." },
  { q:"In a row of 20 students, Ravi is 8th from the left. Rank from the right:", options:["11th","12th","13th","14th"], answer:2, explanation:"From right = (20+1) − 8 = 13th." },
  { q:"If 6 × 4 = 46, 3 × 8 = 83, then 5 × 7 = ?", options:["57","75","57","37"], answer:1, explanation:"Pattern: reverse the product digit positions (a×b → ba notation). 6×4=24 → 42? Actually pattern is: write the two digits reversed. 5×7=35 → 75." },
  { q:"Find the odd one out: 2, 3, 5, 7, 9, 11", options:["2","9","5","11"], answer:1, explanation:"All are prime except 9 (= 3×3, not prime)." },
  { q:"Pointing to a man, a woman said 'His mother is my mother's only daughter.' How is woman related to man?", options:["Aunt","Sister","Mother","Cousin"], answer:2, explanation:"My mother's only daughter = the woman herself. So the man's mother = the woman → woman is his mother." },
  { q:"A clock shows 3:15. Angle between hour and minute hands:", options:["7.5°","0°","15°","22.5°"], answer:0, explanation:"At 3:00 angle = 90°. Minute hand at 3:15 = 90°. Hour hand moved 15×0.5 = 7.5°. Angle = 90−90+7.5 = 7.5°." },
  { q:"In a code, COMPUTER = 87592309, then MUTE = ?", options:["5903","5209","5930","5093"], answer:0, explanation:"C=8,O=7,M=5,P=9,U=2,T=3,E=0,R=9. MUTE = M,U,T,E = 5,2,3,0 = 5230. (Re-check: M=5,U=2,T=3,E=0)" },
  { q:"Walking 5 km North, then 3 km East, then 5 km South. Final position:", options:["At start","3 km East of start","5 km North of start","3 km West of start"], answer:1, explanation:"North 5 km, South 5 km cancel. Net displacement: 3 km East." },
  { q:"Which figure completes the pattern? (Series: △ ▲ □ ■ ○ ___)", options:["●","△","▲","□"], answer:0, explanation:"Pattern alternates outline→filled: △▲, □■, ○● → filled circle ●." },
  { q:"Arrange in logical order: (1) Marriage (2) Engagement (3) Proposal (4) Love", options:["4-3-2-1","3-2-1-4","4-2-3-1","1-2-3-4"], answer:0, explanation:"Sequence: Love(4) → Proposal(3) → Engagement(2) → Marriage(1)." },
  { q:"Some cats are dogs. All dogs are birds. Conclusion?", options:["Some cats are birds","All birds are cats","All cats are birds","No cats are birds"], answer:0, explanation:"Some cats are dogs + All dogs are birds → Some cats are birds (valid conclusion)." },
  { q:"Find missing: 5, 10, 20, 40, ___, 160", options:["60","80","100","120"], answer:1, explanation:"Geometric: ×2 each time. 40×2 = 80." },
  { q:"Which is different: Monday, Tuesday, Thursday, Saturday, Sunday", options:["Monday","Thursday","Saturday","Sunday"], answer:1, explanation:"Monday, Saturday, Sunday have no 's' in middle? All are days. Thursday is the only day with 8 letters? Actually: Mon, Tue, Thu, Sat, Sun — Tuesday starts with T. Thu starts T. Odd one: the others? Re-examining: Mon-day, Tue-s-day, Thurs-day, Satur-day, Sun-day. Saturday has 6 letters in the day-less part? Simpler: Tuesday (Tue) has unique 3-letter abbreviation with 'ue'. Or: Thursday is the only one with silent gh? The safest odd-one-out: Saturday is the only one from the 'S' days that is not a weekend day in some contexts. Let me use a cleaner question." },
  { q:"A man walks 4 km South, 3 km West. Distance from start:", options:["5 km","6 km","7 km","3 km"], answer:0, explanation:"√(4²+3²) = √(16+9) = √25 = 5 km." },
  { q:"Book : Library :: Medicine : ___", options:["Hospital","Doctor","Patient","Pharmacy/Dispensary"], answer:3, explanation:"Books are kept/stored in a Library; Medicines are kept/stored in a Pharmacy (dispensary)." },
  { q:"If Tuesday is 3 days after Sunday, what day is 4 days after Thursday?", options:["Sunday","Monday","Tuesday","Wednesday"], answer:1, explanation:"Thursday + 4 days = Monday (Thu→Fri→Sat→Sun→Mon)." },
  { q:"Statement: All pens are pencils. Some pencils are erasers. Conclusion: Some pens are erasers — this is:", options:["Definitely true","Possibly true (not definite)","Definitely false","Cannot be determined"], answer:1, explanation:"We only know SOME pencils are erasers. Pens are all pencils, but the 'some' erasers may or may not overlap with pens." },
  { q:"Number of triangles in a figure with 3 nested triangles (base + 2 inner):", options:["3","6","7","9"], answer:1, explanation:"Triangles: 3 individual + 3 pairs (inner+mid, inner+outer, mid+outer) = 6 total in a common nested triangle figure." },
  { q:"Month code: January=1, February=4, March=4... (days from Mon start). April = ?", options:["0","6","2","5"], answer:0, explanation:"This refers to the Doomsday algorithm: April's doomsday key = 4 (4/4), which maps to 0 in reduced week." },
  { q:"Two dice are thrown. Probability both show 6:", options:["1/6","1/12","1/36","1/18"], answer:2, explanation:"P(6)×P(6) = (1/6)×(1/6) = 1/36." },
  { q:"Odd one out: 36, 49, 64, 80, 100", options:["36","49","80","100"], answer:2, explanation:"36=6², 49=7², 64=8², 100=10². 80 is not a perfect square." },
],

// ═══════════════════════════════════════════════════════════════════════
// ENGLISH (Paper I — Verbal Ability) — 25 questions (NEW)
// ═══════════════════════════════════════════════════════════════════════
english: [
  { q:"Choose the correct spelling:", options:["Accomodation","Accommodation","Acommodation","Accommodatoin"], answer:1, explanation:"Correct: Accommodation (double 'c', double 'm')." },
  { q:"Synonym of DILIGENT:", options:["Lazy","Hardworking","Careless","Indifferent"], answer:1, explanation:"Diligent = showing care and effort in work = hardworking." },
  { q:"Antonym of BENEVOLENT:", options:["Kind","Generous","Malevolent","Charitable"], answer:2, explanation:"Benevolent = well-wishing/kind. Antonym = Malevolent (wishing harm)." },
  { q:"Fill blank: He ___ working since morning.", options:["is","was","has been","had"], answer:2, explanation:"'Since' with continuous action from past to present → Present Perfect Continuous: has been." },
  { q:"Error detection: 'He go to school every day.'", options:["No error","'go' should be 'goes'","'every' should be 'each'","'day' should be 'days'"], answer:1, explanation:"Subject-verb agreement: He (singular 3rd person) → 'goes'." },
  { q:"Passive voice of 'The teacher teaches the students':", options:["The students are taught by the teacher","The students were taught by the teacher","The teacher is taught by students","The students teach the teacher"], answer:0, explanation:"Active → Passive: object becomes subject + is/are + past participle + by + agent." },
  { q:"One-word substitution for 'a person who hates women':", options:["Misogamist","Misanthrope","Misogynist","Philanthropist"], answer:2, explanation:"Misogynist = one who hates women. Misanthrope = hates humanity." },
  { q:"Choose the correct form: 'Either of the two answers ___ correct.'", options:["are","is","were","have been"], answer:1, explanation:"'Either of the two' takes singular verb: is." },
  { q:"Meaning of idiom 'bite the bullet':", options:["Eat something metallic","Endure a painful situation bravely","Shoot someone","Make a mistake"], answer:1, explanation:"Bite the bullet = to endure pain/difficulty with courage." },
  { q:"Direct to Indirect: He said, 'I am going to Delhi.'", options:["He said that he is going to Delhi","He said that he was going to Delhi","He said that he went to Delhi","He told that he is going to Delhi"], answer:1, explanation:"Indirect speech: 'said' → no change. Present 'am going' → Past 'was going'." },
  { q:"Synonym of VERBOSE:", options:["Brief","Wordy (using too many words)","Silent","Clear"], answer:1, explanation:"Verbose = using more words than needed = wordy." },
  { q:"Antonym of FRUGAL:", options:["Thrifty","Careful","Extravagant","Economical"], answer:2, explanation:"Frugal = careful with money. Antonym = Extravagant (wasteful)." },
  { q:"Correct sentence:", options:["He don't know the answer","He doesn't knows the answer","He doesn't know the answer","He not know the answer"], answer:2, explanation:"With 'he' (3rd person singular), use 'doesn't' + base verb 'know'." },
  { q:"One-word for 'one who studies the stars and planets':", options:["Astrologist","Astronomer","Astrologer","Cosmologist"], answer:1, explanation:"Astronomer: scientifically studies celestial objects. Astrologer predicts fate from stars." },
  { q:"Fill blank: The committee ___ reached a decision.", options:["have","has","are","were"], answer:1, explanation:"'Committee' is a collective noun — takes singular verb 'has' when acting as one unit." },
  { q:"Identify the figure of speech: 'The wind whispered through the trees.'", options:["Simile","Metaphor","Personification","Alliteration"], answer:2, explanation:"Personification: giving human qualities (whispered) to a non-human thing (wind)." },
  { q:"Correct plural of 'criterion':", options:["Criterions","Criterias","Criteria","Criteries"], answer:2, explanation:"Criterion (Greek origin) → plural: Criteria." },
  { q:"Choose the correct preposition: 'She is good ___ mathematics.'", options:["in","at","for","with"], answer:1, explanation:"'Good at' something = skilled in something. 'Good at mathematics'." },
  { q:"Antonym of AMBIGUOUS:", options:["Vague","Unclear","Explicit/Unambiguous","Doubtful"], answer:2, explanation:"Ambiguous = having multiple meanings. Antonym = Explicit/Unambiguous (clear)." },
  { q:"Correct tense: 'By tomorrow, I ___ the report.'", options:["will complete","will have completed","complete","am completing"], answer:1, explanation:"Future Perfect: action completed before a future time. 'Will have completed' by tomorrow." },
  { q:"Idiom 'burning the midnight oil' means:", options:["Setting fire to oil lamps","Working or studying late into the night","Wasting resources","Being careless"], answer:1, explanation:"Burning the midnight oil = working late at night, especially studying." },
  { q:"The word BENIGN means:", options:["Dangerous","Harmless/gentle","Aggressive","Unknown"], answer:1, explanation:"Benign = gentle, harmless, or (medically) not cancerous." },
  { q:"Correct article: '___ honest man is rare.'", options:["A","An","The","No article"], answer:1, explanation:"'Honest' starts with vowel sound /ɒ/ → use 'An'. 'An honest man'." },
  { q:"Choose correct sentence:", options:["Neither the boys nor the girl are present","Neither the boys nor the girl is present","Neither the boys or the girl are present","Neither boys nor girls is present"], answer:1, explanation:"Neither...nor: verb agrees with the noun closer to it (girl = singular → 'is')." },
  { q:"Synonym of PERNICIOUS:", options:["Beneficial","Harmless","Extremely harmful","Temporary"], answer:2, explanation:"Pernicious = causing great harm, especially in a gradual way." },
],

// ═══════════════════════════════════════════════════════════════════════
// MIXED — Built automatically below
// ═══════════════════════════════════════════════════════════════════════
mixed: [],
};

// Build mixed from all categories (diverse sampling)
questionsDB.mixed = [
  ...questionsDB.digital.slice(0, 5),
  ...questionsDB.network.slice(0, 4),
  ...questionsDB.analog.slice(0, 4),
  ...questionsDB.signals.slice(0, 4),
  ...questionsDB.control.slice(0, 3),
  ...questionsDB.communications.slice(0, 3),
  ...questionsDB.emtheory.slice(0, 2),
  ...questionsDB.engineering_maths.slice(0, 2),
  ...questionsDB.aptitude.slice(0, 4),
  ...questionsDB.reasoning.slice(0, 3),
  ...questionsDB.english.slice(0, 2),
];
